---
name: "🛠️ Show Nomad Attributes"
description: |
  This GitHub Action shows FD.io Nomad attributes on the self-hosted runner.

runs:
  using: "composite"
  steps:
    - name: Show Nomad Attributes
      shell: bash
      id: show-nomad-attributes
      run: |
        set -euo pipefail
        if [ -f /etc/os-release ]; then
            . /etc/os-release
        else
            echo "OS information file /etc/os-release not found!"
            exit 1
        fi
        OS_ARCH=$(uname -m)
        LINE="*******************************************************************"
        NOMAD_CLIENT_FILE="/scratch/nomad/nomad-client"
        if [ -f "$NOMAD_CLIENT_FILE" ]; then
            NOMAD_CLIENT_NAME=$(cat "$NOMAD_CLIENT_FILE")
        else
            NOMAD_CLIENT_NAME="Nomad Client Name Unknown"
        fi
        echo "$LINE"
        echo "Executor Runtime Attributes:"
        echo "OS: ${NAME:-"OS Name Unknown"} ${VERSION:-"OSVersion Unknown"}"
        echo "Architecture: $OS_ARCH"
        echo "Nomad Client Name: $NOMAD_CLIENT_NAME"
        echo "Container ID: $(hostname)"
        echo "$LINE"
