---
name: "🛠️ Show Nomad Dockerfile"
description: |
  This GitHub Action shows FD.io Nomad Dockerfile on the self-hosted runner.

runs:
  using: "composite"
  steps:
    - name: Show Nomad Dockerfile
      shell: bash
      id: show-nomad-dockerfile
      run: |
          set -euo pipefail
          LINE="*******************************************************************"
          DOCKERFILE_PATH="/scratch/docker-build/Dockerfile"
          echo "$LINE"
          if [ -f "$DOCKERFILE_PATH" ]; then
              FILE_DELIMITER="----- %< -----"
              echo "Executor Dockerfile: $DOCKERFILE_PATH"
              echo "$FILE_DELIMITER"
              cat "$DOCKERFILE_PATH"
              echo "$FILE_DELIMITER"
          else
              echo "No Dockerfile found in /scratch/docker-build."
          fi
          echo "$LINE"